### Listar modelos
GET http://localhost:8080/api/modelos
Accept: application/json

### Cadastrar Booker
POST http://localhost:8080/api/bookers
Content-Type: application/json

{
  "nome": "Booker Teste",
  "telefone": "11999999999",
  "email": "booker.teste@asteria.com"
}

### Listar Bookers
GET http://localhost:8080/api/bookers
Accept: application/json

### Cadastrar Modelo
POST http://localhost:8080/api/modelos
Content-Type: application/json

{
  "nome": "Modelo Teste",
  "nomeArtistico": "Modelo Asteria",
  "dataCadastro": "2026-08-16",
  "status": "ASPIRANTE",
  "bookerId": "24b1f850-7e84-49cc-91d0-1fd9f816dc4d",
  "scouterId": null,
  "percentualComissao": 20.00,
  "telefone": "11988888888",
  "email": "modelo.teste@asteria.com",
  "foto": null
}

### Buscar modelo criada
GET http://localhost:8080/api/modelos/f83414d7-d910-44be-9276-394aeaa72c56
Accept: application/json

### Cadastrar Modelo - Teste timestamps
POST http://localhost:8080/api/modelos
Content-Type: application/json

{
  "nome": "Modelo Teste 2",
  "nomeArtistico": "Modelo Asteria 2",
  "dataCadastro": "2026-08-16",
  "status": "ASPIRANTE",
  "bookerId": "24b1f850-7e84-49cc-91d0-1fd9f816dc4d",
  "scouterId": null,
  "percentualComissao": 20.00,
  "telefone": "11977777777",
  "email": "modelo.teste2@asteria.com",
  "foto": null
}

### Cadastrar Modelo - Teste timestamps 3
POST http://localhost:8080/api/modelos
Content-Type: application/json

{
  "nome": "Modelo Teste 3",
  "nomeArtistico": "Modelo Asteria 3",
  "dataCadastro": "2026-08-16",
  "status": "ASPIRANTE",
  "bookerId": "24b1f850-7e84-49cc-91d0-1fd9f816dc4d",
  "scouterId": null,
  "percentualComissao": 20.00,
  "telefone": "11966666666",
  "email": "modelo.teste3@asteria.com",
  "foto": null
}

### Cadastrar Modelo - Teste final timestamps
POST http://localhost:8080/api/modelos
Content-Type: application/json

{
  "nome": "Modelo Teste 4",
  "nomeArtistico": "Modelo Asteria 4",
  "dataCadastro": "2026-08-16",
  "status": "ASPIRANTE",
  "bookerId": "24b1f850-7e84-49cc-91d0-1fd9f816dc4d",
  "scouterId": null,
  "percentualComissao": 20.00,
  "telefone": "11955555555",
  "email": "modelo.teste4@asteria.com",
  "foto": null
}

### Cadastrar Modelo - Ultimo teste timestamps
POST http://localhost:8080/api/modelos
Content-Type: application/json

{
  "nome": "Modelo Teste 5",
  "nomeArtistico": "Modelo Asteria 5",
  "dataCadastro": "2026-08-16",
  "status": "ASPIRANTE",
  "bookerId": "24b1f850-7e84-49cc-91d0-1fd9f816dc4d",
  "scouterId": null,
  "percentualComissao": 20.00,
  "telefone": "11955555555",
  "email": "modelo.teste4@asteria.com",
  "foto": null
}

### Cadastrar Modelo - Ultimo teste
POST http://localhost:8080/api/modelos
Content-Type: application/json
{
  "nome": "Modelo Validação",
  "nomeArtistico": "Asteria Validação",
  "dataCadastro": "2026-08-16",
  "status": "ASPIRANTE",
  "bookerId": "24b1f850-7e84-49cc-91d0-1fd9f816dc4d",
  "scouterId": null,
  "percentualComissao": 20.00,
  "telefone": "11944444444",
  "email": "validacao@asteria.com",
  "foto": null
}

### Cadastrar Modelo - Ultimo teste timestamps
POST http://localhost:8080/api/modelos
Content-Type: application/json

{  "nome": "Modelo Validação",
  "nomeArtistico": "Asteria Validação",
  "dataCadastro": "2026-08-16",
  "status": "ASPIRANTE",
  "bookerId": "24b1f850-7e84-49cc-91d0-1fd9f816dc4d",
  "scouterId": null,
  "percentualComissao": 20.00,
  "telefone": "11944444444",
  "email": "validacao@asteria.com",
  "foto": null
}